import type { Metadata } from "next";
import Image from "next/image";
import Container from "@/components/ui/Container";

const PRIMARY_DOMAIN = "https://brokenearrecords.com";

const ABOUT_HERO = "/images/about-hero.jpg";

const CONTACT_EMAIL = "info@brokenearrecords.com";

export const metadata: Metadata = {
  title: "About",
  description:
    "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
  alternates: {
    canonical: `${PRIMARY_DOMAIN}/about`,
  },
  openGraph: {
    title: "About | Broken Ear Records",
    description:
      "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
    url: `${PRIMARY_DOMAIN}/about`,
    images: [
      {
        url: ABOUT_HERO,
        width: 1200,
        height: 630,
        alt: "Broken Ear Records",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "About | Broken Ear Records",
    description:
      "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
    images: [ABOUT_HERO],
  },
};

export default function About() {
  return (
    <section className="relative w-full min-h-screen">
      <div className="absolute inset-0 z-0">
        <Image
          src={ABOUT_HERO}
          alt=""
          fill
          priority
          className="object-cover object-center"
          sizes="100vw"
        />
        <div className="absolute inset-0 bg-black/70" aria-hidden />
      </div>

      <Container className="relative z-10 py-20 md:py-28 md:px-8 text-white mix-blend-difference">
        <h1 className="sr-only">About</h1>
        <div className="max-w-3xl space-y-6 text-base font-mono uppercase leading-relaxed tracking-wide text-white">
          <p>
            Broken Ear Records is an independent label based in Los Angeles,
            committed to releasing original, uncompromising work from underground
            artists.
          </p>
          <p>
            We work with artists who tend to defy easy categorization and whose
            work may not fit any particular category or genre. Our mission is to
            present an artist&apos;s vision, undiluted by any commercial constraints or
            considerations.
          </p>
          <p>
            As the vast majority of people now rely on streaming services like
            $potify to enjoy the music they love, discovering new artists has
            never been easier. But this convenience comes at a terrible cost.
            While these platforms can help artists reach a wider audience, that
            exposure simply doesn&apos;t translate to compensation. Nearly all revenue
            flows to the platform owners and shareholders—while the artists who
            make these great fortunes possible receive only a vanishing fraction of
            the immense profits generated by their work. Sound familiar?
          </p>
          <p>
            Broken Ear Records exists to provide the opportunity for artists to
            make their work available to the people who would like to support them
            directly. Each artist maintains full ownership of their work as well as
            100% of proceeds.
          </p>
          <p>Thank you for listening. See you at the next show.</p>

          <p className="border-t border-white/25 pt-8 mt-8">
            <span className="mb-2 block text-base tracking-wide opacity-90">
              Contact
            </span>
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="mt-2 inline-block !text-white visited:!text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              {CONTACT_EMAIL}
            </a>
          </p>
        </div>
      </Container>
    </section>
  );
}
