import type { Metadata } from "next";
import Container from "@/components/ui/Container";
import { typography } from "@/components/ui/Typography";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://example.com";

export const metadata: Metadata = {
  title: "About",
  description:
    "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
  alternates: {
    canonical: `${siteUrl}/about`,
  },
  openGraph: {
    title: "About | Broken Ear Records",
    description:
      "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
    url: `${siteUrl}/about`,
  },
  twitter: {
    title: "About | Broken Ear Records",
    description:
      "Broken Ear Records is an independent label based in Los Angeles, committed to releasing original, uncompromising work from underground artists.",
  },
};

export default function About() {
  return (
    <Container maxWidth="max-w-3xl" className="py-8">
      <h1 className={`${typography.h1} mb-6`}>About</h1>
      <div className="prose prose-lg">
        <p className="mb-4">
          Broken Ear Records is an independent label based in Los Angeles,
          committed to releasing original, uncompromising work from underground
          artists.
        </p>
        <p className="mb-4">
          We work with artists who tend to defy easy categorization and whose
          work may not fit any particular category or genre. Our mission is to
          present an artist's vision, undiluted by any commercial constraints or
          considerations.
        </p>
        <p className="mb-4">
          As the vast majority of people now rely on streaming services like
          $potify to enjoy the music they love, discovering new artists has
          never been easier. But this convenience comes at a terrible cost.
          While these platforms can help artists reach a wider audience, that
          exposure simply doesn't translates to compensation. Nearly all revenue
          flows to the platform owners and shareholders—while the artists who
          make these great fortunes possible receive only a vanishing fraction of
          the immense profits generated by their work. Sound familiar?
        </p>
        <p className="mb-4">
          Broken Ear Records exists to provide the opportunity for artists to
          make their work available to the people who would like to support them
          directly. Each artist maintains full ownership of their work as well as
          100% of proceeds.
        </p>
        <p className="mb-4">
          Thank you for listening. See you at the next show.
        </p>
      </div>
    </Container>
  );
}
